### ISSUE TITLE
A suggestion about calling convention

### ISSUE THREAD

**Issue by David-Reguera-Garcia-Dreg** [rwfpl/rewolf-wow64ext#5]
Hi ReWolf, I have a suggestion for the project, I can do it and make a pull request if you want:

The exported APIs *64: VirtualFreeEx64, ReadProcessMemory64 etc, are "kind" of binding to Windows APIs. The Windows APIs are stdcall and the lib use other calling convention.

Why the calling convention of the *64 exported functions is not WINAPI stdcall?? 

We can change this, what you think?

I am using getprocaddress to get some symbols from wow64 lib and kernel32.dll and the declaration is like:

typedef SIZE_T (* VirtualQueryEx64_ptr_f)(HANDLE hProcess, DWORD64 lpAddress, MEMORY_BASIC_INFORMATION64* lpBuffer, SIZE_T dwLength)

typedef SIZE_T (WINAPI * VirtualQueryEx32_ptr_f)(HANDLE hProcess, DWORD lpAddress, MEMORY_BASIC_INFORMATION32* lpBuffer, SIZE_T dwLength)

IMO this makes no sense, maybe is better make all stdcall like Windows API.

PD: Sorry for my english.

**Comment by rwfpl** [comment]
Hi Dreg, actually I don't remember why I didn't set __stdcall since the beginning (there are 2 possibilities: I forgot, or I had some reason :)). To maintain backward compatibility I would leave default calling convention, so if someone wants to update only wow64ext component it will not require recompilation of the whole app.

**Comment by David-Reguera-Garcia-Dreg** [comment]
Maybe the reason is X64Call(DWORD64 func, int argC, ...);

stdcall dont works with varargs, and if you do this function first, maybe you do the same for the others.
